services:
  api:
    image: jglchen/chirper-api-jwt
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - chirper-laravel-jwt-sqlite:/app/database

  next:
    image: jglchen/chirper-next-jwt
    ports:
      - 3000:3000

volumes:
  chirper-laravel-jwt-sqlite: